trigger: none

pool:
  name: 'Default'

stages:
- stage: Test
  jobs:
  - job:
    steps:
    - checkout: none
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Key: $(issueKey)"
          Write-Host "Id: $(issueId)"