name: $(Build.DefinitionName)_Ticket_$(issueKey)

trigger: none

pool:
  name: 'Default'

variables:
- group: 'Jira2CP'

stages:
- stage: ProcessTicket
  displayName: Process
  jobs:
  - job: processTicket
    displayName: Process Jira Ticket
    steps:
    - checkout: none
    - task: PowerShell@2
      name: logTicketInfo
      displayName: Log Ticket Info
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Parameters received from Jira:"
          Write-Host "Issue Key                : '$(issueKey)'"
          Write-Host "Issue Id                 : '$(issueId)'"
          Write-Host "Issue Status             : '$(issueStatus)'"
          Write-Host "Issue Status Name        : '$(issueStatusName)'"
          Write-Host "Issue Assignee           : '$(issueAssignee)'"
          Write-Host "Code Pipeline Assignment : '$(issueCpAssignment)'"
    # Create an assignment, in case the assignment has not been set for the ticket in question
    - task: PowerShell@2
      name: createAssignment
      displayName: Create Assignment
      condition: eq(variables['issueCpAssignment'], '<none>')
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Creating new Assignment for Jira Ticket $(issueKey)."

          $requestHeaders = @{}
          $requestHeaders.add("Authorization", "$(cesToken)")
          $requestHeaders.add("Content-Type", "application/json")

          $requestBody  = '{
            "stream": "$(cpStream)",
            "application": "$(cpApplication)",
            "subAppl": "$(cpSubApp)",
            "defaultPath": "$(cpAssignmentDefaultPath)",
            "description": "$(issueSummary)",
            "owner": "$(cpAssignmentOwner)",
            "assignmentPrefix": "$(cpAssignmentPrefix)",
            "referenceNumber": "$(issueKey)"
          }'
          
          $errorMessage = ""
          $restUri      = "$(cesUrl)/ispw/$(cpRuntime)/assignments"

          Write-Host "Calling Url:"
          Write-Host $restUri
          Write-Host "Using Body:"
          Write-Host $requestBody

          try{
              $response   = Invoke-WebRequest -Method POST -Uri $restUri -Headers $requestHeaders -Body $requestBody
              $statusCode = $response.StatusCode
              Write-Host $statusCode
          }
          catch {
              $statusCode = $_.Exception.Response.StatusCode.value__
              Write-Host "`nAn error occurred for REST call"
              Write-Host $statusCode
              Write-Host $response
              Exit 1
          }

          $assignmentInfo   = ConvertFrom-Json $response
          $assignmentId     = $assignmentInfo.assignmentId

          Write-Host "Assignment created: $(assignmentId)"

          Write-Host "##vso[task.setvariable variable=assignmentId;isoutput=true]$assignmentId"
    - task: PowerShell@2
      name: addAssignment2Ticket
      displayName: Add Assignment to Ticket
      condition: eq(variables['issueCpAssignment'], '<none>')
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Adding Assignment ID $(assignmentId) to Jira Ticket $(issueKey)."

          $requestHeaders = @{}
          $requestHeaders.add("Authorization", "$(jiraToken)")
          $requestHeaders.add("Content-Type", "application/json")

          $requestBody  = '{"fields":{"$(jiraAssignmentFieldId)":"$(createAssignment.assignmentId)"}}'

          $errorMessage = ""
          $restUri      = "$(jiraUrl)/rest/api/2/issue/$(issueId)"

          try{
              $response = Invoke-WebRequest -Method PUT -Uri $restUri -Headers $requestHeaders -Body $requestBody
          }
          catch {
              Write-Host "`nAn error occurred for REST call"
              Write-Host $_
              Exit 1
          }

          Write-Host "Ticket $(issueKey) updated with Assignment ID: $(createAssignment.assignmentId)"    
